name: kotlinWasm
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: gradle

      - name: Build Project
        run: ./gradlew wasmJsBrowserDistribution

      - name: Push to executables branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin

          if ! git ls-remote --exit-code --heads origin executables; then
            echo "executables branch does not exist, creating it"
            git switch --orphan executables
            git rm -rf .
            echo "# Executables Branch" > README.md
            git add README.md
            git commit -m "Initial commit for executables branch"
            git push origin executables
          fi

          # Create a worktree for the executables branch
          git worktree add /tmp/executables executables || git worktree add -B executables /tmp/executables origin/executables

          # Copy build output to worktree
          rm -rf /tmp/executables/*
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* /tmp/executables/

          # Commit and push
          cd /tmp/executables
          git add .
          git commit -m "Update WASM executables from $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
          git push origin executables

